In [1]:
import numpy as np
import pandas as pd

In [52]:
N = 10
K = 5
delta = 0.2

cov_matrix = np.random.randn(N, N)
market_weigths = np.random.randn(N, 1)
error_diagonal = np.random.randn(K, K)
P = np.random.randn(K, N)
Q = np.random.randn(K, 1)

In [53]:
def reverse_optimization(delta, cov_matrix, market_weigths):
    
    excess_returns = delta * np.dot(cov_matrix, market_weigths)
    
    return excess_returns

In [54]:
reverse_optimization(delta, cov_matrix, market_weigths)

array([[-1.09256036],
       [ 0.31404725],
       [-0.31346142],
       [ 0.63039769],
       [ 0.75972184],
       [-0.56318917],
       [-0.45652765],
       [ 0.38452868],
       [-0.9694848 ],
       [ 0.69429561]])

In [55]:
def diag(A, B):
    B_inverse = np.linalg.inv(B)
    
    return np.dot(A.T, np.dot(B_inverse, A))

In [56]:
diag(P, error_diagonal)

array([[ -4.5674295 ,  -2.94059707,   0.33011629,   6.11623944,
          2.61796911,  -5.47149661,   5.31185314,   5.63703581,
          6.95736284,  -5.10529779],
       [  1.58750306,   2.14745958,  -0.03158915,  -0.21286091,
         -0.07364802,   2.97029533,  -2.30337618,  -2.05335275,
         -2.77841606,   3.8152357 ],
       [ -4.51800038,  -1.73543118,   1.49063647,   6.70265163,
          1.79215089,  -3.99010313,   3.58229426,   5.76446082,
          6.09663082,  -3.99454333],
       [-16.58945315,  -7.76202975,   2.92480045,  20.89835974,
          6.29300933, -16.49942249,  13.31725461,  19.9442718 ,
         25.55140183, -15.62149947],
       [ -5.3909235 ,  -3.42616811,   0.14014602,   5.00005288,
          1.10643353,  -6.76361738,   4.12223109,   5.79280246,
         10.88064599,  -6.35280719],
       [  2.61305758,   2.50753327,  -0.28057746,  -1.46284003,
         -0.71789615,   3.61655839,  -3.24224911,  -3.50436799,
         -3.41113533,   4.56622967],
       [-1

In [57]:
def black_litterman(tau, cov_matrix, P, error_diagonal, excess_returns, views):
    
    scalled_cov_matrix = np.linalg.inv(np.dot(tau, cov_matrix))
    
    P_omega = diag(P, error_diagonal)
    
    Factor1 = np.linalg.inv(scalled_cov_matrix + P_omega)
    
    Factor2 = np.dot(scalled_cov_matrix, excess_returns) + np.dot(P.T, np.dot(error_diagonal, views))
    
    return np.dot(Factor1, Factor2)

In [58]:
tau = 0.5
excess_returns = reverse_optimization(delta, cov_matrix, market_weigths)
views = np.random.randn(K, 1)

In [59]:
black_litterman(tau, cov_matrix, P, error_diagonal, excess_returns, views)

array([[-1.77310585],
       [11.30909655],
       [ 0.27150175],
       [-7.72055393],
       [-3.61847335],
       [-2.47906823],
       [ 6.40710094],
       [ 6.67948688],
       [ 2.11463149],
       [ 4.49153419]])